### ISSUE TITLE
Usage Guidance

### ISSUE THREAD

**Issue by k0qed** [arivoir/Open.GooglePhotos#1]
Just a request for some brief guidance on how to get started using this and the associated libraries? Thanks.

**Comment by arivoir** [comment]
Sorry for the lack of documentation. The main class is GooglePhotosClient, and the methods map directly to the rest google api.

The constructor of GooglePhotosClient takes the OAuth 2 token that will be used to authenticate.

```
var client  = new GooglePhotosClient("The OAuth Token");
var albums = await client.GetAlbumsAsync();
```

There is a published package in nuget https://www.nuget.org/packages/Open.GooglePhotos/
